version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: leopinnheiro-pgadmin4_server_1
      APP_PORT: 80
  server:
    container_name: pgadmin4
    image: 'dpage/pgadmin4'
    restart: on-failure
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=changeme
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/pgadmin
    ports:
      - '5080:80'
      - '5443:443'
